apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "tu-registro.azurecr.io": {
          "username": "tu-usuario",
          "password": "tu-password",
          "auth": "Y29tby1sb2dyYXItZXN0bw=="
        }
      }
    }
